subscription MessageAdded($conversationId: ID!) {
  messageAdded(conversationId: $conversationId) {
    message {
      id
      content
      createdAt
      sender {
        id
        fullName
      }
    }
  }
}